// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_84HTAvTAtOUKyVpD2F3cqh78KGoP80A',
    appId: '1:715524784111:web:84a35c21207dea5573801a',
    messagingSenderId: '715524784111',
    projectId: 'sentiment-analysis-dca76',
    authDomain: 'sentiment-analysis-dca76.firebaseapp.com',
    storageBucket: 'sentiment-analysis-dca76.appspot.com',
    measurementId: 'G-6DPTDYPFB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcFN0URFA6kEw52mRbLVeyn_xJ8ilNunE',
    appId: '1:715524784111:android:a01ea61deb94386573801a',
    messagingSenderId: '715524784111',
    projectId: 'sentiment-analysis-dca76',
    storageBucket: 'sentiment-analysis-dca76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-AJXJWJL9C-G_tTXqWdhJhDllbA-RRaA',
    appId: '1:715524784111:ios:53e405a602c3f8dd73801a',
    messagingSenderId: '715524784111',
    projectId: 'sentiment-analysis-dca76',
    storageBucket: 'sentiment-analysis-dca76.appspot.com',
    iosBundleId: 'com.example.emotionRecognition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-AJXJWJL9C-G_tTXqWdhJhDllbA-RRaA',
    appId: '1:715524784111:ios:2aba7f00ae0e1a0b73801a',
    messagingSenderId: '715524784111',
    projectId: 'sentiment-analysis-dca76',
    storageBucket: 'sentiment-analysis-dca76.appspot.com',
    iosBundleId: 'com.example.emotionRecognition.RunnerTests',
  );
}
